#!/bin/bash
#Now at target dir
cd /home/ec2-user/startfucks
cp ../settings/config.json ./config.json
cp ../settings/ssl/private-key.pem ./ssl/private-key.pem
cp ../settings/ssl/cert.pem ./ssl/cert.pem
source /home/ec2-user/.bash_profile
npm i -g forever
npm i
npm start